[tool.poetry]
name = "double-fischer-random"
version = "0.1.0"
description = "Analysis of Dasymmetric Double Fischer Random positions"
authors = ["adesso-philipp-schoneville <philipp.schoneville@adesso.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
stockfish = "^3.28.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipython = "^8.21.0"
ipykernel = "^6.29.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
